package ar.com.dalmasso.app.util;

public enum CodeErrors {
    TOKEN_NOT_EQUAL,
    USER_NOT_FOUND,
    USERNAME_NULL_EMPTY,
    PASSWORD_EMPTY,
    TOKEN_INVALID,
    ROLES_NULL_EMPTY,
    ROL_NOT_FOUND,
    TOKEN_INCORRECT,
    USER_REPEATED,
    PASSWORD_NOT_1234,
    PASSWORD_NOT_REGEX,
    PASSWORD_NOT_LENGTH,
    USER_INVALID,
    LOGOUT,
    PASSWORD_EQUAL
}
